RK_device_platform: rk1808
model_framework: onnx
model_file_path: ./model_file/lite-transformer-encoder-16.onnx
quantize: False
dataset: ./encoder_dataset.txt

graph:
  in_0:
    shape: 16,256
  in_1:
    shape: 16,16

configs:
  quantized_dtype: asymmetric_affine-u8
  quantized_algorithm: normal
  optimization_level: 3
  do_sparse_network: True
